version: "3.4"

# Note:
# No underscores in service names or requests
# will be blocked between containers
# https://stackoverflow.com/a/52997937/10381880

services:

  ### BEANSTALK ###

  beanstalk-api:
    entrypoint: /bin/bash
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
      - BEANSTALK_AWS_ACCESS_KEY_ID
      - BEANSTALK_AWS_SECRET_ACCESS_KEY
    # env_file: .env
    environment:
      - LIFEFRAME_API_URL=http://lifeframe-api:8000
      - BEANSTALK_CRON=false
      - REDIS_HOST=beanstalk-redis
      - REDIS_PORT=6379
      - BEANSTALK_DB_HOST=beanstalk-db
      - BEANSTALK_DB_DATABASE_NAME=beanstalk_test_db
      - BEANSTALK_DB_USER=postgres
      - BEANSTALK_DB_PASSWORD=password
      - FILE_STORAGE=django.core.files.storage.FileSystemStorage
      - EMAIL_BACKEND=console
      # - REDIS_PASSWORD=n08sR^*Z^jIju%Ix
    stop_signal: SIGINT
    depends_on:
      - beanstalk-db
      - beanstalk-redis
      # - lifeframe-db
      # - lifeframe-api
    stdin_open: true
    tty: true
    ports:
      - ${BEANSTALK_PUBLIC_API_PORT:-8000}:8000
      # 3000 is the common port for python debugging with vscode
      - ${BEANSTALK_PYTHON_DEBUG_PORT:-3000}:3000
    # volumes:
    #   - .:/app
    networks:
      - lemco_bridge_network
    expose:
      - 8000


  beanstalk-redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    # redis-server command with --save 20 1
    # instructs the server to save 1 or more writes every 20 seconds
    # to disk in case the server restarts
    # command: redis-server --save 20 1 --loglevel warning --requirepass n08sR^*Z^jIju%Ix
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - beanstalk_redis_cache:/data
    networks:
      - lemco_bridge_network

  beanstalk-db:
    image: postgis/postgis:14-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beanstalk_test_db
    ports:
      - ${BEANSTALK_DB_HOST_MAPPED_PORT:-5432}:5432
    volumes:
      # Persist database state between docker sessions/builds
      - beanstalk_db_volume:/var/lib/postgresql/data
    networks:
      - lemco_bridge_network

volumes:
  beanstalk_db_volume:
  lifeframe_db_volume:
  beanstalk_redis_cache:


networks:
  lemco_bridge_network:
    driver: bridge
