# Generated by Django 4.1.1 on 2023-01-05 19:59

import api.models.abstract.admin_mentions_html
import api.models.user
import api.validators
from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=150, unique=True, validators=[api.validators.UsernameCharacterValidator()], verbose_name='username')),
                ('email', api.models.user.LowercaseEmailField(max_length=254, unique=True, validators=[api.validators.LowercaseEmailValidator(), django.core.validators.EmailValidator()], verbose_name='email address')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('verification_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='verification code')),
                ('code_requested_at', models.DateTimeField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to='profile_pictures')),
                ('profile_picture_thumbnail', models.ImageField(blank=True, max_length=1000, null=True, upload_to='profile_pictures')),
                ('life_frame_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='LifeFrame ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('experience_visibility', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Invite'), (3, 'Private')], default=1)),
                ('badge_visibility', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Invite'), (3, 'Private')], default=1)),
                ('activity_push_pref', models.BooleanField(default=True, help_text='Overall notification preference. If this is false, no non-message notifications will be triggered', verbose_name='General notification preference')),
                ('like_push_pref', models.BooleanField(default=True, verbose_name='Like notification preference')),
                ('mention_push_pref', models.BooleanField(default=True, verbose_name='Mention notification preference')),
                ('comment_push_pref', models.BooleanField(default=True, verbose_name='Comment notification preference')),
                ('follow_push_pref', models.BooleanField(default=True, verbose_name='New or accepted follow notification preference')),
                ('follow_request_push_pref', models.BooleanField(default=True, verbose_name='New incoming follow request notification preference')),
                ('accept_complete_push_pref', models.BooleanField(default=True, verbose_name='Experience and Bucket list accept or complete notification preference')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('photo', models.ImageField(max_length=1000, upload_to='badges')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('photo', models.ImageField(max_length=1000, upload_to='badges')),
                ('category', models.IntegerField(blank=True, help_text='LifeFrame ID', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BucketList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, max_length=1000, null=True, upload_to='file_uploads')),
                ('highlight_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='file_uploads')),
                ('highlight_image_thumbnail', models.ImageField(blank=True, null=True, upload_to='file_uploads')),
                ('start_time', models.DateTimeField(blank=True, help_text="If the exact time of day is not needed, set time to midnight 00:00:00,            and check 'Start time date only'. Time is saved in UTC.", null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text="If the exact time of day is not needed, set time to midnight 00:00:00,            and check 'End time date only, Time is saved in UTC.", null=True)),
                ('start_time_date_only', models.BooleanField(default=True)),
                ('end_time_date_only', models.BooleanField(default=True)),
                ('use_local_time', models.BooleanField(default=True, help_text="Checked: different, relative timezone's 1pm based on user location. Unchecked: Exactly 1pm UTC.")),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('editability', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Invite'), (3, 'Private')], default=3)),
                ('visibility', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Invite'), (3, 'Private')], default=1)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bucket_lists', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, api.models.abstract.admin_mentions_html.AdminMentionsHtml),
        ),
        migrations.CreateModel(
            name='BucketListCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_completions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('show_in_picker', models.BooleanField()),
                ('picker_sequence', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='category_mappings')),
                ('overlay_opacity', models.FloatField(default=0.2, help_text='White panel between the background image/color and the text. (Must be a number between 0 and 1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Hex color - Defaults black if blank and no background image,white if blank and has background image', max_length=7)),
                ('background_color', models.CharField(blank=True, help_text='Hex color - Defaults white if blank or invalid color', max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=2000)),
                ('bucket_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, max_length=1000, null=True, upload_to='file_uploads')),
                ('highlight_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='file_uploads')),
                ('highlight_image_thumbnail', models.ImageField(blank=True, null=True, upload_to='file_uploads')),
                ('start_time', models.DateTimeField(blank=True, help_text="If the exact time of day is not needed, set time to midnight 00:00:00,            and check 'Start time date only'. Time is saved in UTC.", null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text="If the exact time of day is not needed, set time to midnight 00:00:00,            and check 'End time date only, Time is saved in UTC.", null=True)),
                ('start_time_date_only', models.BooleanField(default=True)),
                ('end_time_date_only', models.BooleanField(default=True)),
                ('use_local_time', models.BooleanField(default=True, help_text="Checked: different, relative timezone's 1pm based on user location. Unchecked: Exactly 1pm UTC.")),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(validators=[api.validators.non_zero_validator]), blank=True, help_text='LifeFrame IDs', null=True, size=None)),
                ('description', models.CharField(blank=True, max_length=100000, null=True)),
                ('directions', models.CharField(blank=True, max_length=1000, null=True)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Easy'), (20, 'Moderate'), (30, 'Difficult'), (40, 'Extreme'), (100, 'At Own Risk Unrated')], null=True)),
                ('visibility', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Invite'), (3, 'Private')], default=1)),
                ('geo_tag', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=1000, null=True)),
                ('requested_categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, help_text='Not found in LifeFrame, will be checked periodically and removed if found.', size=None)),
                ('categories_need_manual_review', models.BooleanField(default=False, help_text='If checked, this Experience has unknown requested categories from the import script and needs manual attention OR a requested category matches more than 1 LifeFrame category and needs a human to decide')),
                ('qc_reviewed', models.BooleanField(default=False, help_text='This field will be removed soon')),
                ('cost_needs_review', models.BooleanField(default=False, help_text='This field will be removed soon')),
                ('cost_description', models.TextField(blank=True, help_text='This field will be removed soon', null=True)),
                ('original_id', models.IntegerField(blank=True, db_index=True, help_text='This field will be removed soon', null=True)),
                ('original_data', models.TextField(blank=True, help_text='This field will be removed soon', null=True)),
            ],
            bases=(models.Model, api.models.abstract.admin_mentions_html.AdminMentionsHtml),
        ),
        migrations.CreateModel(
            name='ExperienceCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_completions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('codename', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, max_length=1000, null=True, upload_to='file_uploads')),
                ('highlight_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='file_uploads')),
                ('highlight_image_thumbnail', models.ImageField(blank=True, null=True, upload_to='file_uploads')),
                ('text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Invite'), (3, 'Private')], default=1)),
                ('bucket_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('bucket_list_completion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bucketlistcompletion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
                ('experience_completion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experiencecompletion')),
                ('likes', models.ManyToManyField(related_name='post_likes', through='api.Like', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='posts_mentioned_in', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
            bases=(models.Model, api.models.abstract.admin_mentions_html.AdminMentionsHtml),
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows_of_self', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_of_self', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Spam'), (1, 'Explicit Nudity'), (2, 'Dangerous Acts'), (3, 'Abusive Content'), (4, 'Child Abuse'), (5, 'Violence'), (6, 'Visually Disturbing'), (7, 'Drugs'), (8, 'Gambling'), (9, 'Hate Symbols'), (10, 'Terrorism'), (11, 'False Information'), (100, 'Other')])),
                ('details', models.CharField(blank=True, max_length=5000, null=True)),
                ('cron_emailed', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('bucket_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offending_reports', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
        migrations.CreateModel(
            name='PowerProfileAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_control_children', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(help_text='LifeFrame ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceStarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_star_rating_users', to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('experiences', models.ManyToManyField(related_name='experience_stacks', to='api.experience')),
                ('users_followed', models.ManyToManyField(related_name='followed_experience_stacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceSponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='api.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_saves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceCostRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_accepts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='cost_ratings',
            field=models.ManyToManyField(blank=True, related_name='experience_cost_ratings', through='api.ExperienceCostRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='likes',
            field=models.ManyToManyField(related_name='experience_likes', through='api.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='experience_mentioned_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='star_ratings',
            field=models.ManyToManyField(through='api.ExperienceStarRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EarnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Invite'), (3, 'Private')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.badge')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
                ('experience_stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experiencestack')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, null=True)),
                ('last_check_in', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experience'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='comment_likes', through='api.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='comments_mentioned_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
        migrations.CreateModel(
            name='BucketListUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.BooleanField(default=False)),
                ('allowed_to_add', models.IntegerField(default=0)),
                ('num_added', models.IntegerField(default=0)),
                ('action_page_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BucketListStarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_star_rating_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BucketListSponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='api.bucketlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BucketListSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_saves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BucketListPin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_pins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BucketListAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_accepts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='experiences',
            field=models.ManyToManyField(related_name='bucket_lists', to='api.experience'),
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='likes',
            field=models.ManyToManyField(related_name='bucket_list_likes', through='api.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='bucket_lists_mentioned_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='star_ratings',
            field=models.ManyToManyField(through='api.BucketListStarRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BadgePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Complete To Earn'), (2, 'Limited Amount'), (3, 'Limited Time')], default=1)),
                ('earn_until', models.DateTimeField(help_text='For type ENDS_AT')),
                ('earn_limit', models.IntegerField(blank=True, help_text='For type EARN_LIMIT', null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.badge')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='attachments')),
                ('thumbnail', models.ImageField(blank=True, max_length=1000, null=True, upload_to='attachments')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Image'), (2, 'Video'), (3, 'Other')])),
                ('sequence', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('bucket_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
                ('experience_completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experiencecompletion')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
        migrations.CreateModel(
            name='AggregateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Received Message'), (100, 'Mentioned Experience'), (101, 'Mentioned Bucket List'), (102, 'Mentioned Experience Stack'), (103, 'Mentioned Post'), (104, 'Mentioned Comment'), (200, 'Liked Experience'), (201, 'Liked Bucket List'), (202, 'Liked Experience Stack'), (203, 'Liked Post'), (204, 'Liked Comment'), (300, 'Commented Experience'), (301, 'Commented Bucket List'), (302, 'Commented Experience Stack'), (303, 'Commented Post'), (304, 'Commented Comment'), (400, 'Accepted Experience'), (401, 'Completed Experience'), (402, 'Accepted Bucket List'), (403, 'Completed Bucket List'), (500, 'Follow New'), (501, 'Follow Accepted'), (502, 'Follow Request'), (600, 'Added To Your Bucket List'), (601, 'Removed From Bucket List'), (602, 'Added Your Experience To Bucket List')])),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_time', models.DateTimeField(blank=True, null=True)),
                ('bucket_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('comment', models.ForeignKey(blank=True, help_text='The comment that all aggregated related_users commented on. It is the parent of all aggregated related_comments.', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
                ('experience_stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experiencestack')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post')),
                ('related_comment', models.ForeignKey(blank=True, help_text='The most recent aggregated comment. Its parent is the comment field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_related_comment', to='api.comment')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_related_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aggregate activities',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Received Message'), (100, 'Mentioned Experience'), (101, 'Mentioned Bucket List'), (102, 'Mentioned Experience Stack'), (103, 'Mentioned Post'), (104, 'Mentioned Comment'), (200, 'Liked Experience'), (201, 'Liked Bucket List'), (202, 'Liked Experience Stack'), (203, 'Liked Post'), (204, 'Liked Comment'), (300, 'Commented Experience'), (301, 'Commented Bucket List'), (302, 'Commented Experience Stack'), (303, 'Commented Post'), (304, 'Commented Comment'), (400, 'Accepted Experience'), (401, 'Completed Experience'), (402, 'Accepted Bucket List'), (403, 'Completed Bucket List'), (500, 'Follow New'), (501, 'Follow Accepted'), (502, 'Follow Request'), (600, 'Added To Your Bucket List'), (601, 'Removed From Bucket List'), (602, 'Added Your Experience To Bucket List')])),
                ('seen', models.BooleanField(default=False)),
                ('is_push', models.BooleanField(default=False)),
                ('has_pushed', models.BooleanField(default=False)),
                ('aggregated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_time', models.DateTimeField(blank=True, null=True)),
                ('bucket_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('comment', models.ForeignKey(blank=True, help_text='The comment that related_user commented on. It is the parent of related_comment.', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
                ('experience_stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.experiencestack')),
                ('like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.like')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post')),
                ('related_comment', models.ForeignKey(blank=True, help_text='The comment that related_user made to generate this activity. Its parent is the comment field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_comment', to='api.comment')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_bucket_lists',
            field=models.ManyToManyField(blank=True, related_name='users_accepted', through='api.BucketListAccept', to='api.bucketlist'),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_experiences',
            field=models.ManyToManyField(blank=True, related_name='users_accepted', through='api.ExperienceAccept', to='api.experience'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocks',
            field=models.ManyToManyField(through='api.UserBlock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='completed_bucket_list',
            field=models.ManyToManyField(blank=True, related_name='users_completed', through='api.BucketListCompletion', to='api.bucketlist'),
        ),
        migrations.AddField(
            model_name='user',
            name='completed_experiences',
            field=models.ManyToManyField(blank=True, related_name='users_completed', through='api.ExperienceCompletion', to='api.experience'),
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(through='api.UserFollow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='pinned_bucket_lists',
            field=models.ManyToManyField(blank=True, related_name='users_pinned', through='api.BucketListPin', to='api.bucketlist'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_bucket_lists',
            field=models.ManyToManyField(blank=True, related_name='users_saved', through='api.BucketListSave', to='api.bucketlist'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_experiences',
            field=models.ManyToManyField(blank=True, related_name='users_saved', through='api.ExperienceSave', to='api.experience'),
        ),
        migrations.AddField(
            model_name='user',
            name='seen_bucket_lists',
            field=models.ManyToManyField(blank=True, to='api.bucketlist'),
        ),
        migrations.AddField(
            model_name='user',
            name='seen_experiences',
            field=models.ManyToManyField(blank=True, to='api.experience'),
        ),
        migrations.AddField(
            model_name='user',
            name='seen_posts',
            field=models.ManyToManyField(to='api.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('followed_user')), _negated=True), name='no_self_following'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('user', 'followed_user'), name='no_duplicate_follows'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('blocked_user')), _negated=True), name='no_self_blocking'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('user', 'blocked_user'), name='no_duplicate_blocks'),
        ),
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together={('user', 'blocked_user')},
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('experience_completion', None), ('bucket_list_completion', None), _connector='OR'), name='only_complete_experience_or_bucket_list'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('experience_completion', None), _negated=True), models.Q(('experience', None), _negated=True)), ('experience_completion', None), _connector='OR'), name='experience_completions_must_have_experience'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('bucket_list_completion', None), _negated=True), models.Q(('bucket_list', None), _negated=True)), ('bucket_list_completion', None), _connector='OR'), name='bucket_list_completions_must_have_bucket_lists'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('experience', None), _negated=True), models.Q(('bucket_list', None), _negated=True), _connector='OR'), name='must_be_experience_or_bucket_list_post'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.CheckConstraint(check=models.Q(('start_time', None), ('end_time', None), ('start_time__lt', models.F('end_time')), _connector='OR'), name='start_experience_before_end'),
        ),
        migrations.AddConstraint(
            model_name='bucketlist',
            constraint=models.CheckConstraint(check=models.Q(('start_time', None), ('end_time', None), ('start_time__lt', models.F('end_time')), _connector='OR'), name='start_bucket_list_before_end'),
        ),
    ]
