# Generated by Django 4.0.4 on 2023-01-06 21:14

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL('''
            CREATE INDEX upper_exp_name_ginidx
            ON api_experience
            USING GIN (UPPER(name) gin_trgm_ops)
        '''),
        migrations.RunSQL('''
            CREATE INDEX upper_bl_name_ginidx
            ON api_bucketlist
            USING GIN (UPPER(name) gin_trgm_ops)
        '''),
        migrations.RunSQL('''
            CREATE INDEX upper_username_ginidx
            ON api_user
            USING GIN (UPPER(name) gin_trgm_ops)
        '''),
    ]
