# Generated by Django 4.1.1 on 2023-01-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trigram_indexing'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(db_index=True, default="This is a post. I'm the title!", max_length=500),
            preserve_default=False,
        ),
    ]
