# Generated by Django 4.1.1 on 2023-01-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='completed_bucket_list',
            new_name='completed_bucket_lists',
        ),
    ]
