# Generated by Django 4.1.1 on 2023-01-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_completed_bucket_list_user_completed_bucket_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='not_publicly_viewable_reason',
            field=models.CharField(blank=True, help_text='Be professional, the creator of this content may see this reason. If they are able to fix the issue, we may enable publicly_viewable', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='publicly_viewable',
            field=models.BooleanField(default=True, help_text='If unchecked, this content will be remove from being searched, queried, completed, etc.'),
        ),
        migrations.AddField(
            model_name='comment',
            name='not_publicly_viewable_reason',
            field=models.CharField(blank=True, help_text='Be professional, the creator of this content may see this reason. If they are able to fix the issue, we may enable publicly_viewable', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='publicly_viewable',
            field=models.BooleanField(default=True, help_text='If unchecked, this content will be remove from being searched, queried, completed, etc.'),
        ),
        migrations.AddField(
            model_name='experience',
            name='not_publicly_viewable_reason',
            field=models.CharField(blank=True, help_text='Be professional, the creator of this content may see this reason. If they are able to fix the issue, we may enable publicly_viewable', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='publicly_viewable',
            field=models.BooleanField(default=True, help_text='If unchecked, this content will be remove from being searched, queried, completed, etc.'),
        ),
        migrations.AddField(
            model_name='post',
            name='not_publicly_viewable_reason',
            field=models.CharField(blank=True, help_text='Be professional, the creator of this content may see this reason. If they are able to fix the issue, we may enable publicly_viewable', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publicly_viewable',
            field=models.BooleanField(default=True, help_text='If unchecked, this content will be remove from being searched, queried, completed, etc.'),
        ),
    ]
