# Generated by Django 4.1.1 on 2023-01-12 16:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_publicly_viewable_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='requested_categories',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                help_text='Not found in LifeFrame, will be checked periodically and removed if found.',
                null=True,
                size=None),
        ),
    ]
