# Generated by Django 4.1.1 on 2023-01-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_experience_requested_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_about_new_content_reports',
            field=models.BooleanField(
                default=False,
                help_text='Will be emailed about new Reports that are created in the mobile app. ' + \
                    'This should be a user who has the ability to resolve Reports, like a member of the Admin group. ' + \
                    'Will not be emailed if not "Email verified" and not "Staff status"'),
        ),
    ]
