# Generated by Django 4.1.1 on 2023-01-17 23:09

import api.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_notify_about_new_content_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='aggregated_categories',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    validators=[api.validators.non_zero_validator]),
                blank=True,
                help_text='LifeFrame IDs',
                null=True,
                size=None),
        ),
    ]
