# Generated by Django 4.1.1 on 2023-01-19 19:27

import api.validators
import django.contrib.postgres.fields.citext
from django.db import migrations
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bucketlist_aggregated_categories'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=150, unique=True, validators=[api.validators.UsernameCharacterValidator()], verbose_name='username'),
        ),
    ]
