# Generated by Django 4.1.1 on 2023-01-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bucketlist_aggregated_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
