# Generated by Django 4.1.1 on 2023-01-23 22:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bucketlist_aggregated_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencecostrating',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_cost_rating_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BucketListCostRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bucketlist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_cost_rating_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='cost_ratings',
            field=models.ManyToManyField(blank=True, related_name='bucket_list_cost_ratings', through='api.BucketListCostRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
