# Generated by Django 4.1.1 on 2023-01-19 19:41

import api.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=api.models.user.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
