# Generated by Django 4.1.1 on 2023-01-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_experiencecostrating_created_by_and_more'),
        ('api', '0009_experience_is_deleted'),
    ]

    operations = [
    ]
