# Generated by Django 4.1.1 on 2023-01-26 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20230125_1754'),
        ('api', '0013_merge_20230125_0107'),
    ]

    operations = [
    ]
