# Generated by Django 4.1.1 on 2023-01-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bucketlist_deleted_at_bucketlist_is_deleted'),
        ('api', '0015_post_deleted_at_post_is_deleted'),
    ]

    operations = [
    ]
