# Generated by Django 4.1.1 on 2023-01-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20230127_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymapping',
            name='category_id',
            field=models.IntegerField(unique=True),
        ),
    ]
