# Generated by Django 4.1.1 on 2023-02-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_categorymapping_category_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='must_be_experience_or_bucket_list_post',
        ),
    ]
