# Generated by Django 4.1.1 on 2023-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_post_must_be_experience_or_bucket_list_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Easy'), (20, 'Moderate'), (30, 'Difficult'), (40, 'Extreme'), (100, 'Unrated')], null=True),
        ),
    ]
