# Generated by Django 4.1.1 on 2023-02-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_experience_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='directions',
        ),
    ]
