# Generated by Django 4.1.1 on 2023-02-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_experience_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='bucket_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.bucketlist'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.experience'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='experience_completion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.experiencecompletion'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.post'),
        ),
    ]
