# Generated by Django 4.1.1 on 2023-02-23 16:29

from django.core.management import call_command
import django.core.validators
from django.db import migrations, models

def _up(apps, schema_editor):
    call_command('convert_geotag_to_lat_lng')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_attachment_bucket_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True,
            validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='experience',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True,
            validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='geo_tag',
            field=models.CharField(blank=True, db_index=True, help_text='This field will be removed soon', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, help_text='Human-readable Google Maps API result', max_length=500, null=True),
        ),
        # migrations.RunPython(_up, migrations.RunPython.noop)
    ]
