# Generated by Django 4.1.1 on 2023-02-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_attachment_bucket_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='highlight_image_thumbnail',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='file_uploads'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='highlight_image_thumbnail',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='file_uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='highlight_image_thumbnail',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='file_uploads'),
        ),
    ]
