# Generated by Django 4.1.1 on 2023-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_bucketlist_highlight_image_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='highlight_image',
            field=models.ImageField(blank=True, default='', max_length=1000, upload_to='file_uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='highlight_image_thumbnail',
            field=models.ImageField(blank=True, default='', max_length=1000, upload_to='file_uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='video',
            field=models.FileField(blank=True, default='', max_length=1000, upload_to='file_uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='highlight_image',
            field=models.ImageField(blank=True, default='', max_length=1000, upload_to='file_uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='highlight_image_thumbnail',
            field=models.ImageField(blank=True, default='', max_length=1000, upload_to='file_uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='video',
            field=models.FileField(blank=True, default='', max_length=1000, upload_to='file_uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='highlight_image',
            field=models.ImageField(blank=True, default='', max_length=1000, upload_to='file_uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='highlight_image_thumbnail',
            field=models.ImageField(blank=True, default='', max_length=1000, upload_to='file_uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, default='', max_length=1000, upload_to='file_uploads'),
            preserve_default=False,
        ),
    ]
