# Generated by Django 4.1.1 on 2023-03-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_experience_latitude_experience_longitude_and_more'),
        ('api', '0023_alter_bucketlist_highlight_image_and_more'),
    ]

    operations = [
    ]
