# Generated by Django 4.1.1 on 2023-03-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20230301_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
