# Generated by Django 4.1.1 on 2023-03-09 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_comment_bucket_list_alter_comment_experience_and_more'),
        ('api', '0025_like_created_at'),
    ]

    operations = [
    ]
