# Generated by Django 4.1.1 on 2023-03-10 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_attachment_deleted_at_attachment_description_and_more'),
        ('api', '0026_merge_20230309_0017'),
    ]

    operations = [
    ]
