# Generated by Django 4.1.1 on 2023-03-27 16:47

import api.models.abstract.admin_mentions_html
import api.validators
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20230310_2311'),
    ]

    operations = [
        migrations.RenameModel(old_name='BucketList',            new_name='Playlist'),
        migrations.RenameModel(old_name='BucketListAccept',      new_name='PlaylistAccept'),
        migrations.RenameModel(old_name='BucketListCompletion',  new_name='PlaylistCompletion'),
        migrations.RenameModel(old_name='BucketListCostRating',  new_name='PlaylistCostRating'),
        migrations.RenameModel(old_name='BucketListPin',         new_name='PlaylistPin'),
        migrations.RenameModel(old_name='BucketListSave',        new_name='PlaylistSave'),
        migrations.RenameModel(old_name='BucketListSponsorship', new_name='PlaylistSponsorship'),
        migrations.RenameModel(old_name='BucketListStarRating',  new_name='PlaylistStarRating'),
        migrations.RenameModel(old_name='BucketListUser',        new_name='PlaylistUser'),
    ]
