# Generated by Django 4.1.1 on 2023-03-27 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_bucketlist_to_playlist'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playlist',
            name='start_bucket_list_before_end',
        ),
        migrations.RemoveConstraint(
            model_name='post',
            name='only_complete_experience_or_bucket_list',
        ),
        migrations.RemoveConstraint(
            model_name='post',
            name='bucket_list_completions_must_have_bucket_lists',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='aggregateactivity',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistaccept',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistcompletion',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistcostrating',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistpin',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistsave',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistsponsorship',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playliststarrating',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistuser',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='bucket_list_completion',
            new_name='playlist_completion',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='bucket_list',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='accepted_bucket_lists',
            new_name='accepted_playlists',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='completed_bucket_lists',
            new_name='completed_playlists',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pinned_bucket_lists',
            new_name='pinned_playlists',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='saved_bucket_lists',
            new_name='saved_playlists',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='seen_bucket_lists',
            new_name='seen_playlists',
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Received Message'), (100, 'Mentioned Experience'), (101, 'Mentioned Playlist'), (102, 'Mentioned Experience Stack'), (103, 'Mentioned Post'), (104, 'Mentioned Comment'), (200, 'Liked Experience'), (201, 'Liked Playlist'), (202, 'Liked Experience Stack'), (203, 'Liked Post'), (204, 'Liked Comment'), (300, 'Commented Experience'), (301, 'Commented Playlist'), (302, 'Commented Experience Stack'), (303, 'Commented Post'), (304, 'Commented Comment'), (400, 'Accepted Experience'), (401, 'Completed Experience'), (402, 'Accepted Playlist'), (403, 'Completed Playlist'), (500, 'Follow New'), (501, 'Follow Accepted'), (502, 'Follow Request'), (600, 'Added To Your Playlist'), (601, 'Removed From Playlist'), (602, 'Added Your Experience To Playlist')]),
        ),
        migrations.AlterField(
            model_name='aggregateactivity',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Received Message'), (100, 'Mentioned Experience'), (101, 'Mentioned Playlist'), (102, 'Mentioned Experience Stack'), (103, 'Mentioned Post'), (104, 'Mentioned Comment'), (200, 'Liked Experience'), (201, 'Liked Playlist'), (202, 'Liked Experience Stack'), (203, 'Liked Post'), (204, 'Liked Comment'), (300, 'Commented Experience'), (301, 'Commented Playlist'), (302, 'Commented Experience Stack'), (303, 'Commented Post'), (304, 'Commented Comment'), (400, 'Accepted Experience'), (401, 'Completed Experience'), (402, 'Accepted Playlist'), (403, 'Completed Playlist'), (500, 'Follow New'), (501, 'Follow Accepted'), (502, 'Follow Request'), (600, 'Added To Your Playlist'), (601, 'Removed From Playlist'), (602, 'Added Your Experience To Playlist')]),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cost_ratings',
            field=models.ManyToManyField(blank=True, related_name='playlist_cost_ratings', through='api.PlaylistCostRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='experiences',
            field=models.ManyToManyField(related_name='playlists', to='api.experience'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='likes',
            field=models.ManyToManyField(related_name='playlist_likes', through='api.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='playlists_mentioned_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistaccept',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_accepts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistcostrating',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_cost_rating_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistpin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_pins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistsave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playliststarrating',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_star_rating_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='accept_complete_push_pref',
            field=models.BooleanField(default=True, verbose_name='Experience and Playlist accept or complete notification preference'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.CheckConstraint(check=models.Q(('start_time', None), ('end_time', None), ('start_time__lt', models.F('end_time')), _connector='OR'), name='start_playlist_before_end'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('experience_completion', None), ('playlist_completion', None), _connector='OR'), name='only_complete_experience_or_playlist'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('playlist_completion', None), _negated=True), models.Q(('playlist', None), _negated=True)), ('playlist_completion', None), _connector='OR'), name='playlist_completions_must_have_playlists'),
        ),
    ]
