# Generated by Django 4.1.1 on 2023-03-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Migration 30 was skipped, it was a migration that set all 3 of these values
        # to max_length=100, no need to set it low just to set it to 250 in this migration.
        ('api', '0029_remove_playlist_start_bucket_list_before_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
