# Generated by Django 4.1.1 on 2023-03-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_custom_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcategory',
            name='needs_manual_review',
            field=models.BooleanField(default=False),
        ),
    ]
