# Generated by Django 4.1.1 on 2023-04-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_experience_created_by_and_more'),
        ('api', '0034_customcategory_needs_manual_review'),
    ]

    operations = [
    ]
