# Generated by Django 4.1.1 on 2023-04-07 15:28

from django.db import migrations


def _up(apps, schema_editor):
    Experience = apps.get_model('api', 'Experience')
    before_delete_count = Experience.objects.count()
    Experience.objects \
        .filter(created_by__isnull=True) \
        .all() \
        .delete()
    after_delete_count = Experience.objects.count()
    deleted_count = before_delete_count - after_delete_count
    if deleted_count > 0:
        print()
        print(f'Deleted {deleted_count} Experience(s) because they had a null created_by')
        print()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_merge_20230405_1814'),
    ]

    operations = [
        migrations.RunPython(_up, migrations.RunPython.noop),
    ]
