# Generated by Django 4.1.1 on 2023-04-07 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _up(apps, schema_editor):
    Playlist = apps.get_model('api', 'Playlist')
    before_delete_count = Playlist.objects.count()
    Playlist.objects \
        .filter(created_by__isnull=True) \
        .all() \
        .delete()
    after_delete_count = Playlist.objects.count()
    deleted_count = before_delete_count - after_delete_count
    if deleted_count > 0:
        print()
        print(f'Deleted {deleted_count} Playlist(s) because they had a null created_by')
        print()



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_experience_created_by_part2'),
    ]

    operations = [
        migrations.RunPython(_up, migrations.RunPython.noop),
    ]
