# Generated by Django 4.1.1 on 2023-04-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_playlist_created_by_part2'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
