# Generated by Django 4.1.1 on 2023-04-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_comment_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='website',
            # Raised max_length up from 1000
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
