# Generated by Django 4.1.1 on 2023-04-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_experience_website'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='experience',
            name='start_experience_before_end',
        ),
        migrations.RemoveConstraint(
            model_name='playlist',
            name='start_playlist_before_end',
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.CheckConstraint(check=models.Q(('start_time', None), ('end_time', None), ('start_time__lte', models.F('end_time')), _connector='OR'), name='start_experience_before_end'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.CheckConstraint(check=models.Q(('start_time', None), ('end_time', None), ('start_time__lte', models.F('end_time')), _connector='OR'), name='start_playlist_before_end'),
        ),
    ]
