# Generated by Django 4.1.1 on 2023-04-20 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_experience_start_experience_before_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePersonalBucketList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_saves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bucket_list',
            field=models.ManyToManyField(blank=True, related_name='users_bucket_list', through='api.SavePersonalBucketList', to='api.experience'),
        ),
    ]
