# Generated by Django 4.1.1 on 2023-05-11 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_savepersonalbucketlist_user_bucket_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='MFAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Sms'), (1, 'Email'), (2, 'Authenticator')])),
                ('seed', models.CharField(default=pyotp.random_base32, max_length=32, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
