# Generated by Django 4.1.1 on 2023-05-10 15:45

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_user_phone_mfaconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearYouMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='near_you')),
                ('is_default', models.BooleanField(default=False, help_text="If checked,         this mapping will be used as a fallback if a user's location data is unavailable.\n         If multiple mappings are marked as default, only the first will be used.")),
                ('latitude', models.FloatField(blank=True, help_text='The latitude of the center of the circle to which this mapping applies', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(blank=True, help_text='The longitude of the center of the circle to which this mapping applies', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('radius', models.PositiveSmallIntegerField(blank=True, help_text='The radius in miles of the circle to which this mapping applies.', null=True, validators=[api.validators.non_zero_validator])),
                ('overlay_opacity', models.FloatField(default=0.2, help_text='White panel between the background image/color and the text. (Must be a number between 0 and 1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Hex color - Defaults black if blank and no background image,white if blank and has background image', max_length=7)),
                ('background_color', models.CharField(blank=True, help_text='Hex color - Defaults white if blank or invalid color', max_length=7, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='nearyoumapping',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('latitude__isnull', False), ('longitude__isnull', False), ('radius__isnull', False)), models.Q(('latitude__isnull', True), ('longitude__isnull', True), ('radius__isnull', True), ('is_default', True)), _connector='OR'), name='must_be_default_if_latitude_or_longitude_or_radius_are_null'),
        ),
    ]
