# Generated by Django 4.1.1 on 2023-05-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_nearyoumapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='menu_link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='purchase_link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='reservation_link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='partner',
            field=models.BooleanField(default=False),
        ),
    ]
