# Generated by Django 4.1.1 on 2023-06-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_experience_menu_link_experience_purchase_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='highlight_image',
            field=models.ImageField(blank=True, db_index=True, max_length=1000, upload_to='file_uploads'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='video',
            field=models.FileField(blank=True, db_index=True, max_length=1000, upload_to='file_uploads'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='highlight_image',
            field=models.ImageField(blank=True, db_index=True, max_length=1000, upload_to='file_uploads'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='video',
            field=models.FileField(blank=True, db_index=True, max_length=1000, upload_to='file_uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='highlight_image',
            field=models.ImageField(blank=True, db_index=True, max_length=1000, upload_to='file_uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, db_index=True, max_length=1000, upload_to='file_uploads'),
        ),
    ]
