# Generated by Django 4.1.1 on 2023-06-19 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_experience_highlight_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='cost_ratings',
            field=models.ManyToManyField(blank=True, related_name='experience_cost_ratings_experiences', through='api.ExperienceCostRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experience',
            name='star_ratings',
            field=models.ManyToManyField(blank=True, related_name='experience_star_ratings_experiences', through='api.ExperienceStarRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experienceaccept',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_users_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiencestarrating',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_star_ratings_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cost_ratings',
            field=models.ManyToManyField(blank=True, related_name='playlist_cost_ratings_playlists', through='api.PlaylistCostRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='star_ratings',
            field=models.ManyToManyField(blank=True, related_name='playlist_star_rating_playlists', through='api.PlaylistStarRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistaccept',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_users_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playliststarrating',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_star_ratings_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
