# Generated by Django 4.1.1 on 2023-06-20 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_experience_cost_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencecompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
