# Generated by Django 4.1.1 on 2023-07-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_experiencecompletion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='custom_categories',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='api.customcategory'),
        ),
    ]
