# Generated by Django 4.1.1 on 2023-07-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_experience_custom_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apple User ID'),
        ),
    ]
