# Generated by Django 4.1.1 on 2023-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_experience_custom_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencesponsorship',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='experiencesponsorship',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlistsponsorship',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistsponsorship',
            name='user',
        ),
        migrations.AddField(
            model_name='categorymapping',
            name='details',
            field=models.CharField(blank=True, help_text='Shows on the category contents page in the app', max_length=2000, null=True),
        ),
    ]
