# Generated by Django 4.1.1 on 2023-07-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_experiencesponsorship_experience_and_more'),
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymapping',
            name='sponsorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsorship.categorysponsorship'),
        ),
        migrations.DeleteModel(
            name='ExperienceSponsorship',
        ),
        migrations.DeleteModel(
            name='PlaylistSponsorship',
        ),
    ]
