# Generated by Django 4.1.1 on 2023-07-21 17:41

from django.db import migrations

def _up(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    content_type = ContentType.objects.filter(
        app_label='api',
        model='user').first()
    if content_type is None:
        # not creating change user email verified permission
        return
    Permission.objects.get_or_create(
        codename='change_user_email_verified',
        name='Can change user email verified',
        content_type=content_type)
    Permission.objects.get_or_create(
        codename='can_manage_user_permissions',
        name='Able to manage user permissions',
        content_type=content_type)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_user_apple_user_id'),
    ]

    operations = [
        migrations.RunPython(
            _up,
            migrations.RunPython.noop
        )
    ]
