# Generated by Django 4.1.1 on 2023-07-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_adding_admin_permissions'),
        ('api', '0050_categorymapping_sponsorship_and_more'),
    ]

    operations = [
    ]
