# Generated by Django 4.1.1 on 2023-07-27 19:35

from django.db import migrations, models

from api.enums import UserType

def _up(apps, schema_editor):
    User = apps.get_model('api', 'User')
    for u in User.objects.filter(partner=True):
        u.user_type = UserType.PARTNER
        u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_manageduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Unverified'), (1, 'Verified'), (2, 'Partner')],
                default=0),
        ),
        migrations.RunPython(_up, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='partner',
        ),
    ]
