# Generated by Django 4.1.1 on 2023-08-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Google User ID'),
        ),
    ]
