# Generated by Django 4.1.1 on 2023-09-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_comment_total_comments_comment_total_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
