# Generated by Django 4.1.1 on 2023-09-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_comment_total_comments_comment_total_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=100000),
        ),
    ]
