# Generated by Django 4.1.1 on 2023-09-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_playlist_description_alter_post_text'),
        ('api', '0056_experience_total_reviews_playlist_total_reviews'),
    ]

    operations = [
    ]
