# Generated by Django 4.1.1 on 2023-09-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_merge_20230913_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook User ID'),
        ),
    ]
