# Generated by Django 4.1.1 on 2023-10-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_user_facebook_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='minutes_offset',
            field=models.IntegerField(
                blank=True,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='device',
            name='os',
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 'Ios'),
                    (2, 'Android'),
                    (3, 'Web'),
                    (4, 'Linux'),
                    (5, 'Windows'),
                    (6, 'Macos')
                ],
                default=None,
                null=True
            ),
        ),
    ]
