# Generated by Django 4.1.12 on 2023-10-09 02:20

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion

def _up(apps, schema_editor):
    from django.contrib.gis.geos import Point
    # Note: GeoDjango documentation says Point(longitude, latitude), in that order
    # Note: srid=4326 ensures the point is stored using WGS84,
    #       the most common coordinate system for latitude and longitude.
    Experience = apps.get_model('api', 'Experience')
    ExperienceLatLong = apps.get_model('api', 'ExperienceLatLong')
    exp_qs = Experience.objects \
        .filter(latitude__isnull=False, longitude__isnull=False)
    for exp in exp_qs:
        point = Point(exp.longitude, exp.latitude, srid=4326)
        ExperienceLatLong.objects.create(
            experience=exp,
            point=point)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_enable_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceLatLong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latlong', to='api.experience')),
            ],
        ),
        migrations.RunPython(_up, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='experiencelatlong',
            index=django.contrib.postgres.indexes.GistIndex(fields=['point'], name='api_experie_point_fc1c4f_gist'),
        ),
    ]
