# Generated by Django 4.1.1 on 2023-10-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_device_minutes_offset_device_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp_of_the_day_push_pref',
            field=models.BooleanField(
                default=True,
                verbose_name='Experience of the day notification preference'),
        ),
    ]
