# Generated by Django 4.1.12 on 2023-10-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_experiencelatlong'),
        ('api', '0060_user_exp_of_the_day_push_pref'),
    ]

    operations = [
    ]
