upstream srv {
    server beanstalk_api:8000;
}

server {
    listen 80;
    listen [::]:80;

    server_name api-staging.thebeanstalkapp.com;
    client_max_body_size 400m;

    # Static files weren't applying after loading in Django admin,
    # the fix was to include mime.types so their mime type gets
    # set properly, they were being loaded as text.
    include /etc/nginx/mime.types;

    location /static {
        alias /static;
    }

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_redirect off;
        proxy_pass http://srv;
    }
}

#### DEFAULT ####
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location /healthcheck {
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host            'api-staging.thebeanstalkapp.com';
        proxy_set_header X-NginX-Proxy   true;
        proxy_redirect   off;
        proxy_pass       http://srv;
    }

    location / {
        # 444 is special nginx's non-standard code, if 444 is returned that closes the connection.
        # Not used right now as it will make the load balancer return a 503. Instead we will return a raw 404
        # return 444; # "Connection closed without response"
        return 404; # Raw basic 404
    }
}
