# Generated by Django 4.1.1 on 2023-07-20 18:59

import api.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysponsorship',
            name='cost',
            field=models.PositiveIntegerField(blank=True, help_text='In pennies, for example: $10.00 = 1000', null=True),
        ),
        migrations.AddField(
            model_name='categorysponsorship',
            name='notes',
            field=models.TextField(blank=True, help_text='This field is for admin note taking, will not show in the app', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='categorysponsorship',
            name='details',
            field=models.CharField(blank=True, help_text="Text that will show up above the category's details in the app while this sponsorship is active", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='categorysponsorship',
            name='experience_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(validators=[api.validators.non_zero_validator]), blank=True, help_text='Comma separated Challenge IDs, for example: 100,156,4954', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='categorysponsorship',
            name='image',
            field=models.ImageField(blank=True, help_text='Image that will replace the category image in the app while this sponsorship is active', max_length=1000, null=True, upload_to='category_sponsorships'),
        ),
    ]
