# Generated by Django 4.1.1 on 2023-09-14 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0057_merge_20230913_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceOfTheDaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_at', models.DateTimeField(db_index=True, help_text="Treat this like the user's local time. If set to 1pm, will go live at 1pm for every user no matter where they are in the world")),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
