# Generated by Django 4.1.1 on 2023-10-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceofthedayschedule',
            name='notify_all_users',
            field=models.BooleanField(default=False, help_text='If true, all users will be notified when this experience goes live or at 9 am, whichever is later.'),
        ),
    ]
